Repository adshayanB/jobMaps, pull requests merged in 2021-08, with the labels that each got.

#168 open new tab for external links
  client/src/components/Resources.js
Labels: enhancement, front-end

#170 Resources page bug
  client/src/components/Resources.js
  client/src/pages/Resourcepage.js
  client/src/styles/_resources.scss
Labels: bug, front-end

#171 Updated filters to allow for multiple status filters
  client/src/components/Filters.js
  client/src/pages/Applications.js
Labels: enhancement, api-integration

#173 Filter status
  client/src/styles/_home.scss
Labels: bug, front-end

#175 Filter company
  client/src/components/Filters.js
  server/src/controllers/appController.js
  server/src/routes/applicationRoutes.js
Labels: front-end, api-integration

#176 Added delete apps feature
  client/src/components/Jobapps.js
  client/src/pages/Applications.js
  client/src/styles/app.scss
  server/src/controllers/appController.js
Labels: front-end, api-integration

#178 Edit UI
  README.md
  client/src/components/Filters.js
  client/src/components/Homenav.js
  client/src/components/Jobapps.js
  client/src/components/Nav.js
  client/src/components/Resources.js
  client/src/pages/Applications.js
  client/src/pages/Resourcepage.js
  client/src/styles/_home.scss
  client/src/styles/_resources.scss
  client/src/styles/app.scss
  server/src/controllers/appController.js
  server/src/routes/applicationRoutes.js
Labels: enhancement, back-end, front-end, api-integration

#179 add calendar ui
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/components/Calendar.js
  client/src/pages/Calendarpage.js
  client/src/styles/app.scss
Labels: enhancement, front-end

#180 Highlight active nav
  client/src/components/Homenav.js
Labels: enhancement, front-end, UX

#181 Edit job title UI
  client/src/components/Jobapps.js
Labels: enhancement, front-end, api-integration

#183 Edit status on ui
  client/src/components/Jobapps.js
  client/src/styles/_home.scss
Labels: enhancement, front-end, api-integration

#185 Update logo
  client/src/images/logo-backup.png
  client/src/images/logo-light.png
  client/src/images/logo-white.png
  client/src/images/logo.png
  client/src/pages/Landingpage.js
Labels: enhancement, front-end, UX

#187 UI for add app
  client/src/App.js
  client/src/components/Jobapps.js
  client/src/pages/AddApps.js
  client/src/styles/_home.scss
Labels: enhancement, front-end, UX

#198 Edit date field validation
  client/src/components/Jobapps.js
Labels: enhancement, good first issue, front-end

#199 Style add job apps page
  client/src/pages/AddApps.js
  client/src/styles/_home.scss
  client/src/styles/app.scss
Labels: enhancement, front-end, UX
