Repository adshayanB/jobMaps, pull requests merged in 2021-09, with the labels that each got.

#200 add apps integrate backend
  client/src/pages/AddApps.js
  client/src/styles/_home.scss
  client/src/styles/app.scss
Labels: front-end, api-integration

#201 show interviews in calendar
  client/src/components/Calendar.js
  client/src/styles/app.scss
Labels: enhancement, front-end

#202 Add job apps
  client/src/components/Filters.js
  client/src/components/Jobapps.js
Labels: bug, front-end
